name: Build Debian-based Linux ISO

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install required tools
      run: sudo apt-get update && sudo apt-get install -y debootstrap xorriso isolinux syslinux squashfs-tools

    - name: Create Debian environment
      run: sudo debootstrap --variant=minbase stable debian_env http://deb.debian.org/debian

    - name: Set up ISOLINUX bootloader
      run: |
        sudo mkdir -p debian_env/isolinux
        sudo cp /usr/lib/ISOLINUX/isolinux.bin debian_env/isolinux/
        sudo cp /usr/lib/syslinux/modules/bios/ldlinux.c32 debian_env/isolinux/
        echo "DEFAULT linux
        LABEL linux
          KERNEL /live/vmlinuz
          APPEND initrd=/live/initrd.img boot=live components" | sudo tee debian_env/isolinux/isolinux.cfg

    - name: Download Kernel and Initrd
      run: |
        sudo chroot debian_env apt-get update
        sudo chroot debian_env apt-get install -y linux-image-amd64 live-boot live-tools live-config os-prober
        KERNEL_VERSION=$(ls debian_env/boot/vmlinuz-* | sed 's|debian_env/boot/vmlinuz-||')
        INITRD_VERSION=$(ls debian_env/boot/initrd.img-* | sed 's|debian_env/boot/initrd.img-||')
        sudo mkdir -p debian_env/live
        sudo cp debian_env/boot/vmlinuz-$KERNEL_VERSION debian_env/live/vmlinuz
        sudo cp debian_env/boot/initrd.img-$INITRD_VERSION debian_env/live/initrd.img

    - name: Add custom startup script
      run: |
        sudo mkdir -p debian_env/lib/live/config
        echo "#!/bin/bash
        echo 'Hello, World!' > /root/startup.log" | sudo tee debian_env/lib/live/config/0010-my-startup-script
        sudo chmod +x debian_env/lib/live/config/0010-my-startup-script

    - name: Prepare live filesystem
      run: |
        sudo mksquashfs debian_env debian_env/live/filesystem.squashfs -e live/isolinux

    - name: Create ISO
      run: |
        sudo xorriso -as mkisofs -r -J -joliet-long -l \
          -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
          -partition_offset 16 -A "Debian-based Linux" \
          -b isolinux/isolinux.bin -c isolinux/boot.cat \
          -no-emul-boot -boot-load-size 4 -boot-info-table \
          -o debian_based_linux.iso debian_env

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: debian_based_linux_iso
        path: debian_based_linux.iso
