name: Build Debian-based Linux ISO

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install required tools
      run: sudo apt-get update && sudo apt-get install -y debootstrap xorriso isolinux syslinux

    - name: Create Debian environment
      run: sudo debootstrap --variant=minbase stable debian_env http://deb.debian.org/debian

    - name: Set up ISOLINUX bootloader
      run: |
        sudo mkdir -p debian_env/isolinux
        sudo cp /usr/lib/ISOLINUX/isolinux.bin debian_env/isolinux/
        sudo cp /usr/lib/syslinux/modules/bios/ldlinux.c32 debian_env/isolinux/
        echo "default linux
        label linux
          kernel /vmlinuz
          append initrd=/initrd.img boot=live" | sudo tee debian_env/isolinux/isolinux.cfg

    - name: Download Kernel and Initrd
      run: |
        sudo chroot debian_env apt-get update
        sudo chroot debian_env apt-get install -y linux-image-amd64 live-boot
        KERNEL_VERSION=$(ls debian_env/boot/vmlinuz-* | sed 's|debian_env/boot/vmlinuz-||')
        sudo cp debian_env/boot/vmlinuz-$KERNEL_VERSION debian_env/vmlinuz
        sudo cp debian_env/boot/initrd.img-$KERNEL_VERSION debian_env/initrd.img

    - name: Create ISO
      run: |
        sudo xorriso -as mkisofs -r -J -joliet-long -l \
          -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
          -partition_offset 16 -A "Debian-based Linux" \
          -b isolinux/isolinux.bin -c isolinux/boot.cat \
          -no-emul-boot -boot-load-size 4 -boot-info-table \
          -o debian_based_linux.iso debian_env

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v2
      with:
        name: debian_based_linux_iso
        path: debian_based_linux.iso
