name: Build and Deploy GRUB Bootable USB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y debootstrap syslinux genisoimage grub-pc-bin

    - name: Create minimal Linux environment
      run: |
        mkdir -p minimal-linux/rootfs
        sudo debootstrap --variant=minbase stable minimal-linux/rootfs

    - name: Copy detect.sh script
      run: |
        sudo cp detect.sh minimal-linux/rootfs/root/

    - name: Install GRUB dependencies
      run: |
        sudo chroot minimal-linux/rootfs /bin/bash -c "apt-get update"
        sudo chroot minimal-linux/rootfs /bin/bash -c "apt-get install -y grub-pc-bin"

    - name: Install GRUB
      run: |
        sudo chroot minimal-linux/rootfs /bin/bash -c "grub-install /dev/sda"

    - name: Execute detect.sh script
      run: |
        sudo chroot minimal-linux/rootfs /bin/bash -c "/root/detect.sh"

    - name: Generate GRUB config file
      run: |
        sudo chroot minimal-linux/rootfs /bin/bash -c "update-grub"

    - name: Generate ISO image
      run: |
        sudo mkisofs -o minimal-linux.iso -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table minimal-linux

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v2
      with:
        name: minimal-linux-iso
        path: minimal-linux.iso
